######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

title: '{0} &n${1}'
previous-menu: true

pattern:
  - '& & & & & & & & &'
  - '% $ A B C D E F %'
  - '% % G H I J K L %'
  - '% * M N O P Q R %'
  - '% % S T U V W X %'
  - '& & & & & & & & &'

items:
  '&':
    type: BLACK_STAINED_GLASS_PANE
    name: '&f'
  '$':
    type: SPAWNER
    name: '&e&lSPAWNERS ->'
  '*':
    type: WRITABLE_BOOK
    name: '&e&lITEMS ->'
  'A':
    block: SPAWNER:IRON_GOLEM
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODkwOTFkNzllYTBmNTllZjdlZjk0ZDdiYmE2ZTVmMTdmMmY3ZDQ1NzJjNDRmOTBmNzZjNDgxOWE3MTQifX19'
    name: '&e&l[!] &7Iron Golem Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'B':
    block: SPAWNER:BLAZE
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjc4ZWYyZTRjZjJjNDFhMmQxNGJmZGU5Y2FmZjEwMjE5ZjViMWJmNWIzNWE0OWViNTFjNjQ2Nzg4MmNiNWYwIn19fQ=='
    name: '&e&l[!] &7Blaze Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'C':
    block: SPAWNER:SPIDER
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDE2NDVkZmQ3N2QwOTkyMzEwN2IzNDk2ZTk0ZWViNWMzMDMyOWY5N2VmYzk2ZWQ3NmUyMjZlOTgyMjQifX19'
    name: '&e&l[!] &7Spider Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'D':
    block: SPAWNER:COW
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ2YzZlZGE5NDJmN2Y1ZjcxYzMxNjFjNzMwNmY0YWVkMzA3ZDgyODk1ZjlkMmIwN2FiNDUyNTcxOGVkYzUifX19'
    name: '&e&l[!] &7Cow Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'E':
    block: SPAWNER:ZOMBIE
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ=='
    name: '&e&l[!] &7Zombie Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'F':
    block: SPAWNER:SKELETON
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzAxMjY4ZTljNDkyZGExZjBkODgyNzFjYjQ5MmE0YjMwMjM5NWY1MTVhN2JiZjc3ZjRhMjBiOTVmYzAyZWIyIn19fQ=='
    name: '&e&l[!] &7Skeleton Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'G':
    block: SPAWNER:CREEPER
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQyNTQ4MzhjMzNlYTIyN2ZmY2EyMjNkZGRhYWJmZTBiMDIxNWY3MGRhNjQ5ZTk0NDQ3N2Y0NDM3MGNhNjk1MiJ9fX0='
    name: '&e&l[!] &7Creeper Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'H':
    block: SPAWNER:ZOMBIFIED_PIGLIN
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2VhYmFlY2M1ZmFlNWE4YTQ5Yzg4NjNmZjQ4MzFhYWEyODQxOThmMWEyMzk4ODkwYzc2NWUwYThkZTE4ZGE4YyJ9fX0='
    name: '&e&l[!] &7Zombified Piglin Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'I':
    block: SPAWNER:GHAST
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGI2YTcyMTM4ZDY5ZmJiZDJmZWEzZmEyNTFjYWJkODcxNTJlNGYxYzk3ZTVmOTg2YmY2ODU1NzFkYjNjYzAifX19'
    name: '&e&l[!] &7Ghast Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'J':
    block: SPAWNER:SLIME
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZhZDIwZmMyZDU3OWJlMjUwZDNkYjY1OWM4MzJkYTJiNDc4YTczYTY5OGI3ZWExMGQxOGM5MTYyZTRkOWI1In19fQ=='
    name: '&e&l[!] &7Slime Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'K':
    block: SPAWNER:GUARDIAN
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGZiNjc1Y2I1YTdlM2ZkMjVlMjlkYTgyNThmMjRmYzAyMGIzZmE5NTAzNjJiOGJjOGViMjUyZTU2ZTc0In19fQ=='
    name: '&e&l[!] &7Guardian Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'L':
    block: SPAWNER:SQUID
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMDE0MzNiZTI0MjM2NmFmMTI2ZGE0MzRiODczNWRmMWViNWIzY2IyY2VkZTM5MTQ1OTc0ZTljNDgzNjA3YmFjIn19fQ=='
    name: '&e&l[!] &7Squid Spawner'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'M':
    block: HOPPER
    type: HOPPER
    name: '&e&l[!] &7Hopper'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'N':
    block: BEACON
    type: BEACON
    name: '&e&l[!] &7Beacon'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'O':
    block: IRON_BLOCK
    type: IRON_BLOCK
    name: '&e&l[!] &7Iron Block'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'P':
    block: GOLD_BLOCK
    type: GOLD_BLOCK
    name: '&e&l[!] &7Gold Block'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'Q':
    block: DIAMOND_BLOCK
    type: DIAMOND_BLOCK
    name: '&e&l[!] &7Diamond Block'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'R':
    block: EMERALD_BLOCK
    type: EMERALD_BLOCK
    name: '&e&l[!] &7Emerald Block'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'S':
    block: BEDROCK
    type: BEDROCK
    name: '&e&l[!] &7Bedrock'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'T':
    block: ENDER_CHEST
    type: ENDER_CHEST
    name: '&e&l[!] &7Ender Chest'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'U':
    block: DRAGON_EGG
    type: DRAGON_EGG
    name: '&e&l[!] &7Dragon Egg'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'V':
    block: CHEST
    type: CHEST
    name: '&e&l[!] &7Chest'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'W':
    block: TRAPPED_CHEST
    type: TRAPPED_CHEST
    name: '&e&l[!] &7Trapped Chest'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'
  'X':
    block: ENCHANTING_TABLE
    type: ENCHANTING_TABLE
    name: '&e&l[!] &7Enchantment Table'
    lore:
      - '&6&l* &e&lQuantity &fx{0}'
      - '&6&l* &e&lWorth: &f${1}'
      - '&6&l* &e&lLevel: &f${2}'